[package]
name = "untitled"  # Название проекта
version = "0.1.0"  # Версия
edition = "2021"   # Версия языка Rust

[dependencies]
roxmltree = "0.20.0"  # This is where dependencies go
rand = "0.8"

[lib]
name = "tests"   # Название библиотеки
path = "tests/src/lib.rs"  # путь к файлу библиотеки
